export const castData = [
  // THE LEADS (VIPs)
  {
    name: "Ramooz Tahir",
    role: "The Groom",
    skill: "The Hero / Infinite Sherwani Stamina",
    side: "groom",
    isVIP: true,
    photo: "ramooz.jpg",
  },
  {
    name: "Maryam Imran",
    role: "The Bride",
    skill: "The Visionary / Negotiation Queen",
    side: "bride",
    isVIP: true,
    photo: "maryam.jpg",
  },
  // THE EXECUTIVE PRODUCERS (VIP Parents)
  {
    name: "Farhat Tahir",
    role: "Mother of the Groom",
    skill: "The Graceful Hostess",
    side: "groom",
    isVIP: true,
    photo: "farhat.jpg",
  },
  {
    name: "Tahir Mehmood",
    role: "Father of the Groom",
    skill: "The Logistic Legend",
    side: "groom",
    isVIP: true,
    photo: "tahir.jpg",
  },
  {
    name: "Muhammad Imran",
    role: "Father of the Bride",
    skill: "The Pillar of Strength",
    side: "bride",
    isVIP: true,
    photo: "imran.jpg",
  },
  {
    name: "Rabiya Imran",
    role: "Mother of the Bride",
    skill: "Chief Emotional Support Officer",
    side: "bride",
    isVIP: true,
    photo: "rabiya.jpg",
  },
  // THE SUPPORTING CAST - BRIDE SIDE
  {
    name: "Sarah Imran",
    role: "Sister of the Bride",
    skill: "Placeholder Skill",
    side: "bride",
    isVIP: false,
    photo: "sarah.jpg",
  },
  {
    name: "Ali Imran",
    role: "Brother of the Bride",
    skill: "Joota Chupai Specialist",
    side: "bride",
    isVIP: false,
    photo: "ali.jpg",
  },
  {
    name: "Aaminah Imran",
    role: "Sister of the Bride",
    skill: "Unpaid Merchandise Manufacturer",
    side: "bride",
    isVIP: false,
    photo: "aaminah.jpg",
  },
  {
    name: "Ayesha Imran",
    role: "Sister of the Bride",
    skill: "The Supreme Leader of Children",
    side: "bride",
    isVIP: false,
    photo: "ayeshaI.jpg",
  },
  // THE SUPPORTING CAST - GROOM SIDE
  {
    name: "Ariha Tahir",
    role: "Sister of the Groom",
    skill: "Placeholder Skill",
    side: "groom",
    isVIP: false,
    photo: "ariha.jpg",
  },
  {
    name: "Aqib Sajjad",
    role: "Brother-in-law",
    skill: "Placeholder Skill",
    side: "groom",
    isVIP: false,
    photo: "aqib.jpg",
  },
  {
    name: "Waqas Tahir",
    role: "Brother of the Groom",
    skill: "Placeholder Skill",
    side: "groom",
    isVIP: false,
    photo: "waqas.jpg",
  },
  {
    name: "Laiba Waqas",
    role: "Sister-in-law",
    skill: "Placeholder Skill",
    side: "groom",
    isVIP: false,
    photo: "laiba.jpg",
  },
  {
    name: "Fatima Tahir",
    role: "Sister of the Groom",
    skill: "Placeholder Skill",
    side: "groom",
    isVIP: false,
    photo: "fatima.jpg",
  },
  {
    name: "Ayesha Tahir",
    role: "Sister of the Groom",
    skill: "Placeholder Skill",
    side: "groom",
    isVIP: false,
    photo: "ayeshaT.jpg",
  },
];